In [1]:
import sys
import pyspark
import os

print(sys.executable)
print(pyspark.__version__)
print(os.environ.get("SPARK_HOME"))

/home/w3e63/pyspark-iceberg-project/.venv/bin/python3
4.1.3
/home/w3e63/spark-4.1.3-bin-hadoop3

In [2]:
from src.core.spark_session import SparkSessionFactory

spark = SparkSessionFactory.create()

WARNING: Using incubator modules: jdk.incubator.vector
:: loading settings :: url = jar:file:/home/w3e63/spark-4.1.3-bin-hadoop3/jars/ivy-2.5.3.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/w3e63/.ivy2.5.2/cache
The jars for the packages stored in: /home/w3e63/.ivy2.5.2/jars
org.apache.iceberg#iceberg-spark-runtime-4.1_2.13 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-a39a37db-8214-472a-b96c-8977c8bce541;1.0
	confs: [default]
	found org.apache.iceberg#iceberg-spark-runtime-4.1_2.13;1.11.0 in central
:: resolution report :: resolve 130ms :: artifacts dl 4ms
	:: modules in use:
	org.apache.iceberg#iceberg-spark-runtime-4.1_2.13;1.11.0 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-a39a37db-8214-472a-b96c-8977c8bce541
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/7ms)
26/08/07 12:14:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [3]:
print(spark.version)

4.1.3

In [4]:
df = spark.table("local.bookings")
df.show()

[Stage 0:>                                                          (0 + 1) / 1]

+--------------+--------------------+-----------+---------+--------+-------------+--------------+-------+--------------+------------+--------+--------------------+-------+----------------+-----------+
|transaction_id|      conversion_key|property_id|   status|currency|check_in_date|check_out_date|revenue|travel_purpose|country_code|site_key|referral_property_id| device|          region|revenue_usd|
+--------------+--------------------+-----------+---------+--------+-------------+--------------+-------+--------------+------------+--------+--------------------+-------+----------------+-----------+
|    7843159206|k-htl_d-d_u-Nzg0M...|  BC-782119|cancelled|     EUR|   2026-07-20|    2026-07-26|  45.89|      business|          FR|     HTL|           BC-212141|desktop|          Europe|      52.91|
|    7843159555|k-htl_d-t_u-Nzg0M...|  BC-782468|  pending|     EUR|   2026-07-15|    2026-07-20|  53.32|        family|          IT|     HTL|           BC-418084| tablet|          Europe|      61.48|
|    7843160174|k-htl_d-t_u-Nzg0M...|  BC-783087|cancelled|     EUR|   2026-07-24|    2026-07-26|  62.33|      business|          FR|     HTL|           BC-807949| tablet|          Europe|      71.87|
|    7843160404|k-pxl_d-m_u-Nzg0M...|  BC-783317|cancelled|     EUR|   2026-07-22|    2026-07-24|  26.24|        family|          DE|     PXL|           BC-146505| mobile|          Europe|      30.25|
|    7843160439|k-bk_d-t_u-Nzg0Mz...|  BC-783352| approved|     EUR|   2026-07-17|    2026-07-24|  31.88|      business|          IT|      BK|           BC-922544| tablet|          Europe|      36.76|
|    7843161083|k-ota_d-d_u-Nzg0M...|  BC-783996|  pending|     EUR|   2026-07-23|    2026-07-24|  66.16|        family|          DE|     OTA|           BC-522892|desktop|          Europe|      76.28|
|    7843161282|k-ota_d-m_u-Nzg0M...|  BC-784195|  pending|     EUR|   2026-07-15|    2026-07-18|  19.15|      business|          IT|     OTA|           BC-861860| mobile|          Europe|      22.08|
|    7843161471|k-ota_d-d_u-Nzg0M...|  BC-784384|cancelled|     JPY|   2026-07-23|    2026-07-25|  16.86|       leisure|          JP|     OTA|           BC-963217|desktop|            Asia|       0.11|
|    7843161488|k-pxl_d-t_u-Nzg0M...|  BC-784401| approved|     EUR|   2026-07-18|    2026-07-20|  14.60|      business|          FR|     PXL|           BC-985654| tablet|          Europe|      16.83|
|    7843161595|k-htl_d-t_u-Nzg0M...|  BC-784508| approved|     USD|   2026-07-21|    2026-07-28|  38.04|        family|          US|     HTL|           BC-635753| tablet|Northern America|      38.04|
|    7843162011|k-bk_d-m_u-Nzg0Mz...|  BC-784924|cancelled|     JPY|   2026-07-16|    2026-07-20|  11.60|      business|          JP|      BK|           BC-958845| mobile|            Asia|       0.07|
|    7843162078|k-bk_d-t_u-Nzg0Mz...|  BC-784991|cancelled|     EUR|   2026-07-20|    2026-07-23|  74.14|       leisure|          DE|      BK|           BC-928174| tablet|          Europe|      85.48|
|    7843162108|k-htl_d-d_u-Nzg0M...|  BC-785021| approved|     EUR|   2026-07-16|    2026-07-22|  46.59|        family|          DE|     HTL|           BC-282695|desktop|          Europe|      53.72|
|    7843162181|k-htl_d-t_u-Nzg0M...|  BC-785094|cancelled|     JPY|   2026-07-19|    2026-07-25|  58.82|        family|          JP|     HTL|           BC-912155| tablet|            Asia|       0.37|
|    7843162862|k-bk_d-t_u-Nzg0Mz...|  BC-785775|  pending|     USD|   2026-07-23|    2026-07-27|  37.86|      business|          US|      BK|           BC-537990| tablet|Northern America|      37.86|
|    7843163543|k-htl_d-m_u-Nzg0M...|  BC-786456|cancelled|     EUR|   2026-07-15|    2026-07-18|  18.53|      business|          FR|     HTL|           BC-552468| mobile|          Europe|      21.36|
|    7843163720|k-ota_d-d_u-Nzg0M...|  BC-786633| approved|     USD|   2026-07-15|    2026-07-19|  16.78|      business|          US|     OTA|           BC-539582|desktop|Northern America|      16.78|
|    7843164051|k-pxl_d-d_u-Nzg0M...|  BC-786964|cancelled|     EUR|   2026-07-20|    2026-07-23|   9.39|       leisure|          IT|     PXL|           BC-584165|desktop|          Europe|      10.83|
|    7843164433|k-ota_d-m_u-Nzg0M...|  BC-787346| approved|     EUR|   2026-07-18|    2026-07-19|  28.05|       leisure|          DE|     OTA|           BC-831665| mobile|          Europe|      32.34|
|    7843164435|k-htl_d-t_u-Nzg0M...|  BC-787348|cancelled|     USD|   2026-07-18|    2026-07-21|  35.30|      business|          US|     HTL|           BC-463906| tablet|Northern America|      35.30|
+--------------+--------------------+-----------+---------+--------+-------------+--------------+-------+--------------+------------+--------+--------------------+-------+----------------+-----------+
only showing top 20 rows

In [5]:
df.printSchema()

root
 |-- transaction_id: string (nullable = true)
 |-- conversion_key: string (nullable = true)
 |-- property_id: string (nullable = true)
 |-- status: string (nullable = true)
 |-- currency: string (nullable = true)
 |-- check_in_date: date (nullable = true)
 |-- check_out_date: date (nullable = true)
 |-- revenue: decimal(18,2) (nullable = true)
 |-- travel_purpose: string (nullable = true)
 |-- country_code: string (nullable = true)
 |-- site_key: string (nullable = true)
 |-- referral_property_id: string (nullable = true)
 |-- device: string (nullable = true)
 |-- region: string (nullable = true)
 |-- revenue_usd: decimal(18,2) (nullable = true)

In [6]:
df.count()

7910

In [ ]:
Travel-ETL data from Postgres

In [8]:
pip install pandas sqlalchemy psycopg2-binary

Collecting pandas
  Using cached pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in ./.venv/lib/python3.12/site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
Downloading sqlalchemy-2.0.51-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 2.5 MB/s eta 0:00:00m eta 0:00:010:01:01
Using cached psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
Downloading greenlet-3.5.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (621 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 621.5/621.5 kB 2.8 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Installing collected packages: psycopg2-binary, numpy, greenlet, sqlalchemy, pandas
Successfully installed greenlet-3.5.4 numpy-2.5.1 pandas-3.0.5 psycopg2-binary-2.9.12 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/travel_db"
)

In [4]:
df = pd.read_sql("SELECT * FROM booking_transactions", engine)

df.head()

,id,transaction_id,conversion_key,property_id,status,travel_purpose,country_code,currency,check_in_date,check_out_date,site_key,device,referral_property_id,revenue,revenue_usd,created_at,updated_at
0,52,7843159202,k-bk_d-t_u-Nzg0MzE1OTIwMg==_g-OTA1MDYyODA1OC4z...,BC-782115,cancelled,leisure,JP,JPY,2026-05-30,2026-06-02,BK,tablet,BC-550235,85.73,0.54,2026-08-07 06:32:25.487748+00:00,2026-08-07 06:32:25.487756+00:00
1,53,7843159203,k-ota_d-d_u-Nzg0MzE1OTIwMw==_g-NzgxODQ3MTk4NC4...,BC-782116,pending,business,IT,EUR,2026-06-18,2026-06-21,OTA,desktop,BC-523702,72.47,83.56,2026-08-07 06:32:25.487759+00:00,2026-08-07 06:32:25.487760+00:00
2,54,7843159206,k-ota_d-t_u-Nzg0MzE1OTIwNg==_g-MTUwNjE2NTEwNy4...,BC-782119,cancelled,leisure,FR,EUR,2026-05-31,2026-06-02,OTA,tablet,BC-613704,80.69,93.03,2026-08-07 06:32:25.487761+00:00,2026-08-07 06:32:25.487762+00:00
3,55,7843159207,k-bk_d-d_u-Nzg0MzE1OTIwNw==_g-MjQxMzcxNDU1Mi44...,BC-782120,pending,family,US,USD,2026-06-15,2026-06-17,BK,desktop,BC-281618,82.50,82.50,2026-08-07 06:32:25.487763+00:00,2026-08-07 06:32:25.487764+00:00
4,56,7843159208,k-ota_d-d_u-Nzg0MzE1OTIwOA==_g-Njk5NDU3Njc2MC4...,BC-782121,approved,leisure,FR,EUR,2026-06-28,2026-07-03,OTA,desktop,BC-242459,56.33,64.95,2026-08-07 06:32:25.487765+00:00,2026-08-07 06:32:25.487766+00:00

In [7]:
print(f"Total rows: {len(df)}")

Total rows: 711

In [9]:
schema = pd.read_sql("""
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'booking_transactions'
ORDER BY ordinal_position;
""", engine)

schema

             column_name                 data_type
0                     id                   integer
1         transaction_id         character varying
2         conversion_key         character varying
3            property_id         character varying
4                 status         character varying
5         travel_purpose         character varying
6           country_code         character varying
7               currency         character varying
8          check_in_date                      date
9         check_out_date                      date
10              site_key         character varying
11                device         character varying
12  referral_property_id         character varying
13               revenue                   numeric
14           revenue_usd                   numeric
15            created_at  timestamp with time zone
16            updated_at  timestamp with time zone